projects:
  GoAPI2:
    schemaPath: graphql/schema.json
    includes:
      - '*.graphql'
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: GoAPI.swift
        docsFilePath: .
extensions:
  amplify:
    version: 3
