projects:
  GoAPI:
    schemaPath: graphql/schema.json
    includes:
      - '*.graphql'
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: GoAPI.swift
        docsFilePath: graphql
extensions:
  amplify:
    version: 3
